# Generated by Django 4.2.5 on 2023-09-26 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_3', '0002_user_address_user_age_user_email_user_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscription',
            field=models.BooleanField(default=False),
        ),
    ]
