"""create tables

Revision ID: f77a5cbe9334
Revises: 
Create Date: 2023-09-14 13:28:30.380615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f77a5cbe9334'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('surname', sa.String(length=64), nullable=True),
    sa.Column('phone', sa.String(length=12), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_phone'), ['phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_surname'), ['surname'], unique=False)

    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('specification', sa.Text(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_specification'), ['specification'], unique=False)

    op.create_table('seller',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('surname', sa.String(length=64), nullable=True),
    sa.Column('phone', sa.String(length=12), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('date_employ', sa.Date(), nullable=True),
    sa.Column('position', sa.Enum('Продавец', 'Старший продавец', 'Руководитель отдела продаж'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('seller', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_seller_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_seller_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_seller_phone'), ['phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_seller_position'), ['position'], unique=False)
        batch_op.create_index(batch_op.f('ix_seller_surname'), ['surname'], unique=False)

    op.create_table('sale',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_sale', sa.Date(), nullable=True),
    sa.Column('summ', sa.Float(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('seller_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['seller.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sale_summ'), ['summ'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sale_summ'))

    op.drop_table('sale')
    with op.batch_alter_table('seller', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_seller_surname'))
        batch_op.drop_index(batch_op.f('ix_seller_position'))
        batch_op.drop_index(batch_op.f('ix_seller_phone'))
        batch_op.drop_index(batch_op.f('ix_seller_name'))
        batch_op.drop_index(batch_op.f('ix_seller_email'))

    op.drop_table('seller')
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_specification'))
        batch_op.drop_index(batch_op.f('ix_product_name'))

    op.drop_table('product')
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_surname'))
        batch_op.drop_index(batch_op.f('ix_customer_phone'))
        batch_op.drop_index(batch_op.f('ix_customer_name'))
        batch_op.drop_index(batch_op.f('ix_customer_email'))

    op.drop_table('customer')
    # ### end Alembic commands ###
