"""Initial migration.

Revision ID: 0a5a21c69e2e
Revises: 
Create Date: 2023-09-12 12:26:37.626680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a5a21c69e2e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('specialization', sa.String(length=64), nullable=True),
    sa.Column('address', sa.String(length=128), nullable=True),
    sa.Column('website', sa.String(length=64), nullable=True),
    sa.Column('phone', sa.String(length=12), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_restaurant_address'), ['address'], unique=True)
        batch_op.create_index(batch_op.f('ix_restaurant_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_restaurant_phone'), ['phone'], unique=True)
        batch_op.create_index(batch_op.f('ix_restaurant_specialization'), ['specialization'], unique=False)
        batch_op.create_index(batch_op.f('ix_restaurant_website'), ['website'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_restaurant_website'))
        batch_op.drop_index(batch_op.f('ix_restaurant_specialization'))
        batch_op.drop_index(batch_op.f('ix_restaurant_phone'))
        batch_op.drop_index(batch_op.f('ix_restaurant_name'))
        batch_op.drop_index(batch_op.f('ix_restaurant_address'))

    op.drop_table('restaurant')
    # ### end Alembic commands ###
